//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamNo { get; set; }
        public string TeamName { get; set; }
        public string Description { get; set; }
        public int GameNo { get; set; }
        public int MatchesPlayed { get; set; }
        public int MatchesWon { get; set; }
        public int PercentageWin { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
